[package]
name = "credentiald-cli"
version = "1.2.0"
edition = "2021"

[dependencies]
credential-core = { path = "../credential-core" }
credential-crypto = { path = "../credential-crypto" }
credential-store = { path = "../credential-store" }
credential-client = { path = "../credential-client" }
credential-ipc = { path = "../credential-ipc" }
serde_json = "1.0"
directories = { workspace = true }
libc = "0.2"
rpassword = "7"
zeroize = { workspace = true }
argon2 = { workspace = true }
tokio = { workspace = true }
