[package]
name = "sigil-prompter"
version = "1.2.0"
edition = "2021"

[dependencies]
sigil-ipc = { path = "../sigil-ipc" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
iris = { workspace = true }
lens = { workspace = true }
lens-sys = { workspace = true }
flux = { workspace = true }
flux-sys = { workspace = true }
serde_json = "1.0"
